# Generated by Django 3.1 on 2020-08-12 10:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AdminList',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.CharField(max_length=30, unique=True)),
                ('password', models.CharField(max_length=128)),
                ('comp', models.IntegerField()),
                ('mach', models.IntegerField(null=True)),
                ('samp', models.IntegerField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('wday', models.DateField(auto_now_add=True)),
                ('user', models.CharField(max_length=30, unique=True)),
                ('password', models.CharField(max_length=128)),
            ],
        ),
        migrations.CreateModel(
            name='Machinery',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('identnum', models.CharField(max_length=10, unique=True)),
                ('wday', models.DateField(auto_now_add=True)),
                ('buyday', models.DateField()),
                ('run_unit', models.CharField(max_length=10)),
                ('run_hist', models.IntegerField(null=True)),
                ('fuel', models.CharField(max_length=10)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='machinerys', to='machines.company')),
            ],
        ),
        migrations.CreateModel(
            name='TechLeader',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('wday', models.DateField(auto_now_add=True)),
                ('startday', models.DateField()),
                ('email', models.EmailField(default='to1@example.com', max_length=254, unique=True)),
                ('user', models.CharField(max_length=30, unique=True)),
                ('password', models.CharField(max_length=128)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='techleaders', to='machines.company')),
            ],
        ),
        migrations.CreateModel(
            name='Runing',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('wtype', models.CharField(max_length=10)),
                ('start_time', models.DateTimeField()),
                ('end_time', models.DateTimeField()),
                ('start_kmeter', models.IntegerField(null=True)),
                ('end_kmeter', models.IntegerField(null=True)),
                ('machinery', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='runings', to='machines.machinery')),
            ],
        ),
        migrations.CreateModel(
            name='OilSample',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('minta_azonosito', models.CharField(max_length=10, unique=True)),
                ('beerkezes_napja', models.DateField()),
                ('mintaveetel_napja', models.DateField()),
                ('viszkozitas_valtozas', models.SmallIntegerField(null=True)),
                ('koromtartalom', models.FloatField(null=True)),
                ('osszulledek', models.SmallIntegerField(null=True)),
                ('vasm_osszulledek', models.SmallIntegerField(null=True)),
                ('vastartalom', models.SmallIntegerField(null=True)),
                ('viztartalom', models.FloatField(null=True)),
                ('illoanyag', models.FloatField(null=True)),
                ('lobbanaspont', models.SmallIntegerField(null=True)),
                ('kep1', models.ImageField(height_field=300, null=True, upload_to='')),
                ('kep2', models.ImageField(height_field=300, null=True, upload_to='')),
                ('kep3', models.ImageField(height_field=300, null=True, upload_to='')),
                ('machinery', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='oilsamples', to='machines.machinery')),
            ],
        ),
        migrations.CreateModel(
            name='OilChange',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ftime', models.DateTimeField(auto_now_add=True)),
                ('kmeter', models.IntegerField(null=True)),
                ('liter', models.SmallIntegerField()),
                ('machinery', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='oilchanges', to='machines.machinery')),
            ],
        ),
        migrations.CreateModel(
            name='Fueling',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ftime', models.DateTimeField(auto_now_add=True)),
                ('kmeter', models.IntegerField(null=True)),
                ('liter', models.SmallIntegerField()),
                ('machinery', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fuelings', to='machines.machinery')),
            ],
        ),
        migrations.CreateModel(
            name='Driver',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('wday', models.DateField(auto_now_add=True)),
                ('startday', models.DateField()),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('user', models.CharField(max_length=30, unique=True)),
                ('password', models.CharField(max_length=128)),
                ('machinery', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='drivers', to='machines.machinery')),
            ],
        ),
        migrations.CreateModel(
            name='DiagResp',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('wday', models.DateField(auto_now_add=True)),
                ('startday', models.DateField()),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('user', models.CharField(max_length=30, unique=True)),
                ('password', models.CharField(max_length=128)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='diagresps', to='machines.company')),
            ],
        ),
    ]
