# Generated by Django 3.1 on 2020-08-12 13:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('machines', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adminlist',
            name='comp',
            field=models.IntegerField(null=True),
        ),
    ]
