# Generated by Django 3.1 on 2020-08-26 21:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('machines', '0002_auto_20200812_1522'),
    ]

    operations = [
        migrations.AddField(
            model_name='adminlist',
            name='lead',
            field=models.IntegerField(null=True),
        ),
    ]
